# Generated by Django 4.1.7 on 2023-05-16 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2023, 5, 16), verbose_name='date'),
        ),
    ]
