# Generated by Django 4.1.7 on 2023-05-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0003_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='important',
            field=models.CharField(default='no important', max_length=15),
        ),
    ]
