# Generated by Django 4.1.7 on 2023-05-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0004_task_important'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='steps',
            field=models.ManyToManyField(to='ToDoApp.steps'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
