# Generated by Django 4.1.7 on 2023-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0006_remove_task_now_date_task_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Steps',
        ),
        migrations.AlterField(
            model_name='task',
            name='steps',
            field=models.ManyToManyField(to='ToDoApp.step'),
        ),
    ]
