# Generated by Django 4.1.7 on 2023-05-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0008_remove_task_steps_step_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='steps',
            field=models.ManyToManyField(to='ToDoApp.step'),
        ),
    ]
