# Generated by Django 4.1.7 on 2023-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0009_remove_step_task_task_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='status',
            field=models.CharField(default='to do', max_length=10),
        ),
    ]
