# Generated by Django 4.1.7 on 2023-05-18 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0010_step_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='step',
            name='status',
        ),
    ]
