# Generated by Django 4.1.7 on 2023-04-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_shop', '0005_alter_product_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(to='simple_shop.product'),
        ),
    ]
